# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AwAI(object):
    def setupUi(self, AwAI):
        AwAI.setObjectName("AwAI")
        AwAI.resize(1108, 795)
        AwAI.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(AwAI)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(150, 210, 822, 537))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 0, 4, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_12.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 2, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 6)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 0, 5, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_10.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 2, 3, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 2, 2, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_11.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 2, 4, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 0, 3, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 0, 461, 261))
        self.label_2.setStyleSheet("image: url(:/newPrefix/awai.png);")
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, -17, 1061, 51))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2.raise_()
        self.gridLayoutWidget.raise_()
        self.line.raise_()
        AwAI.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AwAI)
        self.statusbar.setObjectName("statusbar")
        AwAI.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(AwAI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1108, 25))
        self.menubar.setObjectName("menubar")
        self.menuOuvrir = QtWidgets.QMenu(self.menubar)
        self.menuOuvrir.setObjectName("menuOuvrir")
        AwAI.setMenuBar(self.menubar)
        self.actionNouvelle_partie = QtWidgets.QAction(AwAI)
        self.actionNouvelle_partie.setObjectName("actionNouvelle_partie")
        self.actionQuitter = QtWidgets.QAction(AwAI)
        self.actionQuitter.setObjectName("actionQuitter")
        self.menuOuvrir.addAction(self.actionNouvelle_partie)
        self.menuOuvrir.addAction(self.actionQuitter)
        self.menubar.addAction(self.menuOuvrir.menuAction())

        self.retranslateUi(AwAI)
        QtCore.QMetaObject.connectSlotsByName(AwAI)

    def retranslateUi(self, AwAI):
        _translate = QtCore.QCoreApplication.translate
        AwAI.setWindowTitle(_translate("AwAI", "AwAI"))
        self.label.setText(_translate("AwAI", "<html><head/><body><p align=\"center\">Image à venir</p></body></html>"))
        self.label_2.setText(_translate("AwAI", "<html><head/><body><p><img src=\":/newPrefix/awai.bmp\"/></p></body></html>"))
        self.menuOuvrir.setTitle(_translate("AwAI", "O&uvrir"))
        self.actionNouvelle_partie.setText(_translate("AwAI", "&Nouvelle partie"))
        self.actionQuitter.setText(_translate("AwAI", "&Quitter"))

import image_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AwAI = QtWidgets.QMainWindow()
    ui = Ui_AwAI()
    ui.setupUi(AwAI)
    AwAI.show()
    sys.exit(app.exec_())

